import Head from "next/head";
import { Content } from "../components/footer/Content";
import { Copyright } from "../components/footer/Copyright";
import { Nav } from "../components/header/Nav";

export default function Home() {
    return (
        <>
            <Head>
                <title>Ancene</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className="relative">
                <Nav />
            </header>

            <main className="flex flex-col">
                <h1>Ancene</h1>

                <footer className="bg-gray-500 py-8 px-4">
                    <Content />

                    <hr className="my-5" />

                    <Copyright />
                </footer>
            </main>
        </>
    );
}
